### ISSUE TITLE
任务前置汇报

### ISSUE THREAD

**Issue by Ledenel** [kcwikizh/kcwiki-report#11]
最近的API变动使得每次进任务窗口都可以获取全部的任务列表了。
统计任务前置现在是可行的：
1. 玩家每次进入任务页面时，记录当前全部的任务信息A；
2. 如果玩家进入后点击了“达成”，完成任务后服务器传下来的新任务包记为B；
3. B中存在但A中不存在的任务记为C；
4. “达成”的任务是C的前置，统计上传即可。

**Comment by b-marisa** [comment]
mission complete
